### ISSUE TITLE
USDT Swaps

### ISSUE THREAD

**Issue by igkoh** [hbdmapi/huobi_futures_Python#45]
Dear Foonsun,

  In huobi_usdt_swap, async def place_orders has orders_data for trader.create_orders as 

{"price": new_price, "quantity": quantity, "action": action, "order_type": ORDER_TYPE_LIMIT, "lever_rate": 1}._

**Question 1:** 
How can I set **USDT Swaps** to have **cross margin mode** instead of isolated margin mode in orders_data or config.json?

Do I add "margin_mode":"cross margin mode"as
{"price": new_price, "quantity": quantity, "action": action, "order_type": ORDER_TYPE_LIMIT, "lever_rate": 1,"margin_mode":"cross margin mode"}
as described in "https://huobiapi.github.io/docs/usdt_swap/v1/en/#query-assets-and-positions-cross-margin-mode".

**Question 2:** 
In  _async def on_event_position_update_, I want to compute Liquidation Price and margin (position, frozen,..)   based on
**cross margin mode.**  What is the **right way to achieve cross margin mode**?

In document, there are POST linear-swap-api/v1/swap_cross_sub_position_info supporting cross margin mode.   I am confused.

**Question 3:** 
Why "huobi_usdt_swap_trade.py" and "huobi_usdt_swap_market.py" in alpha/platforms/ are required instead of using previous swap market and trade?
Are "cross" and "isolated" margin logic to separate out platforms?

Best regards,
Ingyu

**Comment by foonsun** [comment]
Dear Ingyu,

Question 1:
How can I set USDT Swaps to have cross margin mode instead of isolated margin mode in orders_data or config.json?

Cross Margined Mode interfaces will be added in the project later.It's unavailable now.

margin_mode":"cross margin mode" will be passed as parameters of create_orders/create_order interfaces.

Question 2:

Hi, you can use linear-swap-api/v1/swap_cross_account_position_info to get the latest Liquidation price.This interface will be added later.

Question 3:

Hi, "huobi_usdt_swap_market" and "huobi_usdt_swap_trade.py" are similar to the swap market and trade.But indeed there are two systems. The interfaces may not be same.

 "cross" and "isolated" margin logic will be integrated into the same usdt swap platform.

**Comment by igkoh** [comment]
Dear Foonsun,

  Thanks for detailed answers.  I am looking forward to use "cross" and "isolated" margin logic.

Best regards,
Ingyu

**Comment by foonsun** [comment]
Hi,


There will be “USDTSWAP_CROSS” in the config.json to indicate the cross
margined mode.

New platform will be added for The cross mode for simple use.

Best Regards,

foonsun

**Comment by foonsun** [comment]
@igkoh Hi, igkoh. The cross margin mode of usdt swap has been integrated in the alphaquant. feel free to contract with me if any questions.
